### PR TITLE
Add instruction to install jsbi

### LINKED ISSUE #28: Mention JSBI as a new peer dependency in the 1.0 release notes
With the [v1.0.0-rc.1](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/v1.0.0-rc.1) release, the ion-js dependency was upgraded to 4.0.0. The 4.0.0 version has a breaking change which involved making a dependency into a peer dependency. PRs for reference:

- https://github.com/amzn/ion-hash-js/issues/47
- https://github.com/amzn/ion-js/pull/589

If you miss the peer dependency warning when installing the RC and don't install jsbi, you may get the 17 build errors I got that looked a lot like this:

```sh
node_modules/ion-js/dist/commonjs/es6/IonWriter.d.ts:19:18 - error TS2307: Cannot find module 'jsbi'.

19 import JSBI from "jsbi";
```

JSBI is not a module I'm familiar with, but judging by how new it is [here](https://www.npmjs.com/package/jsbi) there's probably a good chance I'm not alone. **I'm opening up this issue to ask that the additional step of installing jsbi gets mentioned in the release notes and/or the README.**

Thank you for the great work on the 1.0 release! I thoroughly enjoyed deleting blocks of Reader step logic today. 🎉

### PR DESCRIPTION
**Pull request by yohanmartin**
Resolves #28 

[Release v1.0.0-rc.1](https://github.com/awslabs/amazon-qldb-driver-nodejs/releases/tag/v1.0.0-rc.1) adds a peerDependency on [jsbi](https://www.npmjs.com/package/jsbi), which users will have to install manually, as noted in [Issue #28 ].

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yohanmartin** [comment]
Add instruction to install jsbi
